<a href="https://colab.research.google.com/github/alfonso-aviles/THC/blob/main/Jueves3deAbril.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [3]:
b = np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [4]:
b%2 == 0

array([False,  True, False,  True, False])

In [5]:
b[b%2==0]

array([2, 4])

In [6]:
MITres=b[np.where(b>=3)]
MITres

array([3, 4, 5])

In [10]:
def factorial(n):
  if type(n)==int:
    factorial=1
    for n in range (1,n+1):
      factorial*=n
    return factorial
  else:
    return "error"

factorial(0)

1