<a href="https://colab.research.google.com/github/alfonso-aviles/THC/blob/main/Martes1deAbril.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Crear una calculadora que acepte dos números y una operación (suma,resta,multiplicación,división)
#como entrada y utilice funciones lamba para realizar la función deseada.
operacion = input("Ingrese la operación que desea realizar (suma,resta,multiplicacion,division): ")
x = int(input("Ingrese el primer número: "))
y = int(input("Ingrese el segundo número: "))
operaciones = {
    "suma": lambda x,y: x+y,
    "resta": lambda x,y: x-y,
    "multiplicacion": lambda x,y: x*y,
    "division": lambda x,y: x/y}
print("El resultado es", operaciones[operacion](x,y))



Ingrese la operación que desea realizar (suma,resta,multiplicacion,division): resta
Ingrese el primer número: 12
Ingrese el segundo número: 12
El resultado es 0


In [13]:
#Crear una calculadora que acepte dos números y una operación (suma,resta,multiplicación,división)
#como entrada y utilice funciones lambda para realizar la función deseada.
operacion = input("Ingrese la operación que desea realizar (suma,resta,multiplicacion,division): ")
x = int(input("Ingrese el primer número: "))
y = int(input("Ingrese el segundo número: "))
def calculadora(x,y,operacion):
  if operacion == "suma":
    suma = lambda x,y: x+y
    resultado = suma(x,y)
  elif operacion == "resta":
    resta = lambda x,y: x-y
    resultado = resta(x,y)
  elif operacion == "multiplicacion":
    multiplicacion = lambda x,y: x*y
    resultado = multiplicacion(x,y)
  elif operacion == "division":
    if y ==0:
      print("No se puede dividir entre cero")
      resultado="indefinido"
    else:
      division = lambda x,y: x/y
      resultado = division(x,y)
  return resultado
print(calculadora(x,y,operacion))

Ingrese la operación que desea realizar (suma,resta,multiplicacion,division): division
Ingrese el primer número: 12
Ingrese el segundo número: 0
No se puede dividir entre cero
indefinido


In [14]:
import random
mylist = ["apple", "banana", "cherry"]
print(random.choice(mylist))

apple


In [39]:
import random
mylist = ["apple", "banana", "cherry","kiwi","grapes"]
print(random.choices(mylist,k=2))

['kiwi', 'cherry']


In [40]:
import numpy as np

In [41]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [43]:
print(arr + 1)
print(arr * 3)
print(arr ** 2)

[2 3 4 5 6]
[ 3  6  9 12 15]
[ 1  4  9 16 25]


In [44]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(arr1 + arr2)

[ 7  9 11 13 15]


In [45]:
arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3)

[[1 2 3]
 [4 5 6]]
